# Generated by Django 2.2.6 on 2020-09-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='author_comments',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='user_post',
        ),
    ]
