# Generated by Django 2.2.6 on 2020-09-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200902_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author_comments',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_post',
            new_name='user',
        ),
    ]
