# Generated by Django 2.2.6 on 2020-09-02 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200902_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='author_comment',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='user_post',
        ),
    ]
