# Generated by Django 2.2.6 on 2020-09-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200903_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author_comment',
            new_name='author',
        ),
    ]
